// =============================================================================
// invoice-metadata.ts — Vizly legal info applied to Stripe customers/invoices
// =============================================================================
// Single source of truth for the legal/fiscal block that must appear on every
// invoice generated by Stripe for Vizly. Branched at customer creation time
// (see getOrCreateCustomerId in src/actions/billing.ts) via
// invoice_settings.footer + invoice_settings.custom_fields, which Stripe
// then automatically inherits onto every future invoice for that customer:
// first charge, renewals, prorated upgrades, cancellation refunds, etc.
//
// Why customer-level and not invoice-level: applying these settings on each
// invoice individually would force us to intercept every invoice creation
// event in the webhook just to patch the footer. Customer-level settings
// are inherited by ALL future invoices automatically — much less code,
// fewer points of failure.
//
// Vizly is a sole proprietorship (entrepreneur individuel) under the French
// franchise en base de TVA regime (art. 293 B du CGI), so prices are net
// and no VAT is collected. If/when Vizly exits this regime, the footer
// here will need to drop the "TVA non applicable" line and the
// STRIPE_TAX_ENABLED env var should be flipped to true (see elements.ts).

/**
 * Multi-line legal footer applied to every Stripe invoice for Vizly customers.
 * Stripe renders this verbatim at the bottom of each PDF invoice.
 */
export const INVOICE_FOOTER_TEXT = `Tom Lefevre Bonzon (Vizly)
18 rue Henri Sée, 35700 Rennes, France
SIREN 103332276 · SIRET 10333227600015 · APE 6201Z
TVA non applicable, art. 293 B du CGI`

/**
 * Stripe customer custom_fields are rendered as a small labeled table near
 * the top of each invoice (above the line items). We surface SIREN/SIRET
 * here for legal traceability — readers see the identifiers prominently
 * even if they don't scroll to the footer.
 *
 * Stripe limits custom_fields to a max of 4 entries per customer.
 */
const INVOICE_CUSTOM_FIELDS = [
  { name: 'SIREN', value: '103332276' },
  { name: 'SIRET', value: '10333227600015' },
] as const

/**
 * Build the invoice_settings payload to pass to stripe.customers.create
 * (or stripe.customers.update) so every future invoice for the customer
 * carries the Vizly legal footer + custom fields.
 *
 * Returned as a plain object (no `as const`) so it composes cleanly with
 * Stripe's CustomerCreateParams.InvoiceSettings type.
 */
export function getCustomerInvoiceSettings() {
  return {
    footer: INVOICE_FOOTER_TEXT,
    custom_fields: INVOICE_CUSTOM_FIELDS.map((f) => ({
      name: f.name,
      value: f.value,
    })),
  }
}
