interface ContentBlock {
  type: 'p' | 'h2' | 'cta'
  text: string
}

const ARTICLES: Record<string, ContentBlock[]> = {
  'creer-portfolio-en-ligne-5-minutes': [
    { type: 'p', text: "Avoir un portfolio en ligne est devenu indispensable en 2026. Que tu sois développeur, designer, photographe ou étudiant, c'est ta vitrine professionnelle. Le problème ? La plupart des outils sont soit trop complexes (WordPress), soit trop chers (Squarespace), soit pas adaptés (Canva exporte un PDF, pas un site). Vizly change ça." },
    { type: 'h2', text: "Étape 1 : Crée ton compte" },
    { type: 'p', text: "Inscris-toi gratuitement avec ton email ou ton compte Google. Pas de carte bancaire demandée. Tu arrives directement dans l'éditeur." },
    { type: 'h2', text: "Étape 2 : Remplis tes informations" },
    { type: 'p', text: "L'éditeur te guide étape par étape. Commence par ton nom, ton métier, ta bio et ta photo de profil. Ajoute tes liens (LinkedIn, GitHub, Dribbble...). Un aperçu en temps réel s'affiche à côté pour voir le résultat au fur et à mesure." },
    { type: 'h2', text: "Étape 3 : Ajoute tes projets" },
    { type: 'p', text: "Pour chaque projet, ajoute un titre, une description, des images (jusqu'à 5) et des tags de compétences. Tu peux réorganiser l'ordre par glisser-déposer. C'est la partie la plus importante de ton portfolio : montre ton meilleur travail." },
    { type: 'h2', text: "Étape 4 : Choisis ton style" },
    { type: 'p', text: "Vizly propose 8 templates uniques, chacun avec sa propre personnalité. Du minimal au brutalist, de l'élégant au bento. Choisis celui qui correspond à ton métier et à ta personnalité. Personnalise les couleurs et la typographie pour le rendre unique." },
    { type: 'h2', text: "Étape 5 : Publie ton portfolio" },
    { type: 'p', text: "Choisis ton pseudo (pseudo.vizly.fr) et publie. Ton site est en ligne instantanément. Tu peux revenir le modifier à tout moment. Le plan gratuit te permet de créer et prévisualiser. Pour la mise en ligne, le plan Starter démarre à 4,99 €/mois." },
    { type: 'cta', text: "Prêt à créer ton portfolio en 5 minutes ?" },
    { type: 'h2', text: "Pourquoi Vizly plutôt qu'un autre outil ?" },
    { type: 'p', text: "Vizly est spécialisé portfolio. Pas un builder de sites générique. L'expérience est optimisée pour un seul objectif : mettre ton travail en valeur rapidement. Pas de drag-and-drop complexe, pas de centaines d'options. Tu remplis, tu personnalises, tu publies. C'est tout." },
    { type: 'p', text: "Chaque template est responsive mobile-first, accessible, et optimisé pour la performance. Ton portfolio charge vite et s'affiche parfaitement sur tous les appareils. Et avec un domaine en .vizly.fr, ton URL est propre et professionnelle." },
  ],

  'portfolio-developpeur-erreurs': [
    { type: 'p', text: "Ton portfolio de développeur est ta meilleure carte de visite. Mais beaucoup de devs font des erreurs qui plombent leur impact. Voici les 10 erreurs les plus courantes et comment les éviter." },
    { type: 'h2', text: "1. Ne pas avoir de portfolio du tout" },
    { type: 'p', text: "L'erreur numéro 1, c'est de se contenter d'un CV et d'un profil LinkedIn. Un portfolio montre ce que tu sais FAIRE, pas juste ce que tu prétends savoir. Les recruteurs et les clients veulent voir du concret." },
    { type: 'h2', text: "2. Lister des technologies sans projets" },
    { type: 'p', text: "\"Je maîtrise React, Node.js, Python, Docker...\" Cool, mais montre-moi. Chaque technologie devrait être illustrée par un projet réel. Un projet bien documenté vaut mieux que 20 logos de technos." },
    { type: 'h2', text: "3. Des projets sans contexte" },
    { type: 'p', text: "Pour chaque projet, explique le problème que tu as résolu, ton rôle, les technologies utilisées, et le résultat. Un screenshot sans explication ne dit rien. Raconte une histoire." },
    { type: 'h2', text: "4. Un design négligé" },
    { type: 'p', text: "\"Je suis dev, pas designer.\" Ce n'est pas une excuse. Un portfolio mal présenté donne l'impression que tu bâcles ton travail. Utilise un template professionnel plutôt que de coder un site moche de zéro." },
    { type: 'cta', text: "Besoin d'un portfolio dev propre en 5 minutes ?" },
    { type: 'h2', text: "5. Trop de projets médiocres" },
    { type: 'p', text: "Qualité > quantité. 3-5 projets bien présentés valent mieux que 15 projets bâclés. Choisis tes meilleurs travaux et mets-les en valeur." },
    { type: 'h2', text: "6. Pas de lien vers le code source" },
    { type: 'p', text: "En tant que dev, ton code est ton portfolio. Ajoute un lien GitHub vers chaque projet. Les recruteurs techniques vont regarder ton code." },
    { type: 'h2', text: "7. Un site qui ne charge pas vite" },
    { type: 'p', text: "Ironie suprême : un dev dont le portfolio met 5 secondes à charger. Optimise tes images, utilise du lazy loading, et choisis un hébergement performant." },
    { type: 'h2', text: "8. Pas de version mobile" },
    { type: 'p', text: "Plus de 50% du trafic web est mobile. Si ton portfolio n'est pas responsive, tu perds la moitié de tes visiteurs. Teste sur téléphone." },
    { type: 'h2', text: "9. Des informations de contact cachées" },
    { type: 'p', text: "Si quelqu'un veut te contacter, ne lui fais pas chercher ton email pendant 3 minutes. Un lien de contact visible, un email clair, des liens LinkedIn/GitHub en évidence." },
    { type: 'h2', text: "10. Ne jamais mettre à jour" },
    { type: 'p', text: "Un portfolio avec des projets de 2022 en 2026, ça fait mauvais effet. Mets à jour régulièrement avec tes derniers projets. Avec Vizly, modifier ton portfolio prend 2 minutes." },
  ],

  'quel-template-choisir': [
    { type: 'p', text: "Vizly propose 8 templates de portfolio, chacun avec sa propre personnalité. Mais lequel est fait pour toi ? Ce guide t'aide à choisir en fonction de ton métier et de ce que tu veux communiquer." },
    { type: 'h2', text: "Tu es développeur ? → Minimal ou Dark" },
    { type: 'p', text: "Le template Minimal est parfait pour les devs : fond blanc, typo clean, projets en grille. Ça laisse parler ton travail sans distraction. Si tu préfères un style plus tech avec un fond sombre et des accents néon, le template Dark est pour toi." },
    { type: 'h2', text: "Tu es étudiant ou junior ? → Classique" },
    { type: 'p', text: "Le template Classique a une structure type CV avec sidebar et liste de projets. C'est rassurant pour les recruteurs qui cherchent un format familier. Idéal pour les candidatures de stage et d'alternance." },
    { type: 'h2', text: "Tu es community manager ou marketeur ? → Coloré" },
    { type: 'p', text: "Le template Coloré respire la créativité et l'énergie. Couleurs vives, layout dynamique, ambiance fun. Parfait pour montrer que tu sais créer du contenu engageant." },
    { type: 'cta', text: "Teste les 4 templates gratuits maintenant" },
    { type: 'h2', text: "Tu es designer ou DA ? → Créatif (Premium)" },
    { type: 'p', text: "Layout asymétrique, grandes images plein écran, animations au scroll. Le template Créatif met ton travail visuel au premier plan. C'est le template le plus impactant pour les portfolios de design." },
    { type: 'h2', text: "Tu es artiste ou designer avant-gardiste ? → Brutalist (Premium)" },
    { type: 'p', text: "Typo bold oversized, layout cassé, grille déconstruite. Le template Brutalist fait une déclaration. C'est pas pour tout le monde, et c'est exactement ce qui le rend mémorable." },
    { type: 'h2', text: "Tu es photographe ou architecte ? → Élégant (Premium)" },
    { type: 'p', text: "Typo serif, espaces généreux, transitions douces. Le template Élégant respire le luxe et le raffinement. Tes images sont mises en valeur comme dans une galerie." },
    { type: 'h2', text: "Tu es product designer ou UI/UX ? → Bento (Premium)" },
    { type: 'p', text: "Le template Bento utilise une grille de blocs de tailles variées. Mix de texte, images et stats dans une composition moderne. Parfait pour les profils polyvalents qui veulent montrer différentes facettes de leur travail." },
  ],

  'portfolio-etudiant-stage-alternance': [
    { type: 'p', text: "Tu cherches un stage ou une alternance ? Ton CV ne suffit plus. En 2026, les recruteurs veulent voir ce que tu sais faire, pas juste lire ce que tu prétends savoir. Un portfolio en ligne, c'est ton avantage compétitif." },
    { type: 'h2', text: "Pourquoi un portfolio est indispensable" },
    { type: 'p', text: "Sur une pile de 200 CV identiques, comment te démarquer ? Un lien vers ton portfolio dans ton CV change la donne. Le recruteur clique, voit tes projets, comprend ton niveau, et te met dans la pile \"à rappeler\". C'est aussi simple que ça." },
    { type: 'h2', text: "Quoi mettre quand on n'a pas d'expérience" },
    { type: 'p', text: "Projets personnels, projets d'école, contributions open source, redesigns conceptuels, challenges de code... Tout compte. L'important c'est de montrer ta démarche, pas d'avoir travaillé chez Google. Un projet scolaire bien présenté vaut mieux que pas de projet du tout." },
    { type: 'h2', text: "Les 5 éléments clés d'un bon portfolio étudiant" },
    { type: 'p', text: "1. Une bio courte et claire qui dit qui tu es et ce que tu cherches. 2. 3 à 5 projets bien documentés avec contexte, techno et résultat. 3. Des visuels (screenshots, mockups, demos). 4. Tes liens (LinkedIn, GitHub). 5. Un moyen de te contacter facilement." },
    { type: 'cta', text: "Crée ton portfolio étudiant gratuitement" },
    { type: 'h2', text: "L'URL qui fait pro" },
    { type: 'p', text: "Avec Vizly, ton portfolio est accessible sur prénom.vizly.fr. C'est propre, facile à retenir, et ça se met dans un CV ou une signature email. Beaucoup plus pro qu'un lien Google Drive ou un PDF envoyé par WeTransfer." },
    { type: 'h2', text: "Combien ça coûte" },
    { type: 'p', text: "Créer et prévisualiser ton portfolio est 100% gratuit. La mise en ligne coûte 4,99 €/mois avec le plan Starter. C'est le prix d'un café par mois pour une vitrine professionnelle accessible 24/7. Et tu peux annuler à tout moment." },
    { type: 'h2', text: "Le bon template pour un étudiant" },
    { type: 'p', text: "On recommande le template Classique : structure type CV, sidebar avec tes infos, projets à droite. Les recruteurs retrouvent un format familier et naviguent facilement. Si tu veux quelque chose de plus moderne, le template Minimal est aussi un excellent choix." },
  ],

  'comparatif-outils-portfolio-2026': [
    { type: 'p', text: "Tu veux créer un portfolio en ligne mais tu ne sais pas quel outil utiliser ? Voici un comparatif honnête des principales solutions en 2026, avec leurs forces et leurs faiblesses." },
    { type: 'h2', text: "WordPress : puissant mais trop complexe" },
    { type: 'p', text: "WordPress peut tout faire, mais c'est justement le problème. Pour un simple portfolio, tu vas passer des heures à configurer un thème, installer des plugins, gérer les mises à jour de sécurité. C'est l'équivalent de prendre un semi-remorque pour aller chercher du pain." },
    { type: 'h2', text: "Wix / Squarespace : beau mais cher" },
    { type: 'p', text: "Ces plateformes sont bien conçues, mais elles ne sont pas spécialisées portfolio. Tu paies 12-20 €/mois pour un builder de sites générique dont tu utiliseras 10% des fonctionnalités. Et les templates portfolio sont souvent génériques." },
    { type: 'h2', text: "Canva : facile mais pas un site web" },
    { type: 'p', text: "Canva est génial pour créer des visuels, mais un \"portfolio Canva\" c'est un PDF ou une image. Pas un site web avec une URL, pas indexé par Google, pas interactif. Ce n'est pas la bonne solution." },
    { type: 'h2', text: "Coder soi-même : contrôle total mais chronophage" },
    { type: 'p', text: "Si tu es dev, tu peux coder ton portfolio from scratch. Mais ça prend du temps : design, responsive, déploiement, maintenance. Du temps que tu pourrais passer à travailler sur de vrais projets. Et 90% des gens ne savent pas coder." },
    { type: 'cta', text: "Essaie Vizly : le juste milieu" },
    { type: 'h2', text: "Carrd : simple mais limité" },
    { type: 'p', text: "Carrd est minimaliste et abordable, mais les portfolios sont limités à une seule page sans vraie gestion de projets. Pas de galerie, pas de templates spécialisés. C'est bien pour une landing page, pas pour un portfolio complet." },
    { type: 'h2', text: "Vizly : spécialisé, simple, abordable" },
    { type: 'p', text: "Vizly est né d'un constat : il n'existe rien de simple, beau et spécialisé portfolio en France. L'expérience est optimisée pour un seul objectif : mettre ton travail en valeur. Formulaire guidé en 5 étapes, 8 templates uniques, publication instantanée sur pseudo.vizly.fr. Le plan gratuit permet de créer et prévisualiser, la mise en ligne démarre à 4,99 €/mois." },
    { type: 'h2', text: "Tableau comparatif" },
    { type: 'p', text: "WordPress : 0-30 €/mois, complexe, personnalisation totale. Wix/Squarespace : 12-20 €/mois, facile, pas spécialisé. Canva : gratuit, pas un site web. Code from scratch : gratuit, très chronophage. Carrd : 5 €/an, limité. Vizly : 0-9,99 €/mois, spécialisé portfolio, templates uniques, publication instantanée." },
  ],
}

export function getArticleContent(slug: string): ContentBlock[] {
  return ARTICLES[slug] ?? []
}
